USE WAREHOUSE COMPUTE_WH;

-- SHOW TASKS AND SUSPEND PARENT (CUSTOMER_INSERT WILL BE PARENT TASK FOR THIS EXAMPLE)
SHOW TASKS;

ALTER TASK CUSTOMER_INSERT SUSPEND;


-- CREATE TABLE
CREATE OR REPLACE TABLE TASK_DB.PUBLIC.CUSTOMERS_CHILD (
    CUSTOMER_ID INT,
    FIRST_NAME  VARCHAR(40),
    CREATE_DATE DATE
);


-- CREATE CHILD TASK
CREATE OR REPLACE TASK CUSTOMER_INSERT_CHILD
    WAREHOUSE = COMPUTE_WH
    AFTER CUSTOMER_INSERT
    AS 
        INSERT INTO TASK_DB.PUBLIC.CUSTOMERS_CHILD 
        SELECT * FROM CUSTOMERS;


-- SHOW TASKS
SHOW TASKS;


-- RESUME PARENT AND CHILD TASKS (CHILD FIRST)
ALTER TASK CUSTOMER_INSERT_CHILD RESUME;
ALTER TASK CUSTOMER_INSERT RESUME;


-- INSPECT DATA
SELECT * FROM TASK_DB.PUBLIC.CUSTOMERS;
SELECT * FROM TASK_DB.PUBLIC.CUSTOMERS_CHILD;


-- SUSPEND TASKS (PARENT FIRST)
ALTER TASK CUSTOMER_INSERT SUSPEND;
ALTER TASK CUSTOMER_INSERT_CHILD SUSPEND;