-- SCALE UP FOR KNOWN PATTERNS OF HIGH WORK LOAD (CHANGING SIZE)
ALTER WAREHOUSE COMPUTE_WH
    SET WAREHOUSE_SIZE = 'LARGE';

ALTER WAREHOUSE COMPUTE_WH
    SET WAREHOUSE_SIZE = 'SMALL';


-- SCALE OUT FOR UNKNOWN PATTERNS OF WORK LOAD (MULTI-CLUSTER WAREHOUSES)
ALTER WAREHOUSE COMPUTE_WH
    SET MAX_CLUSTER_COUNT = 3;