USE WAREHOUSE COMPUTE_WH;


-- SHOW TASKS
SHOW TASKS;


-- QUERY TASK HISTORY
SELECT *
FROM TABLE (INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC;


-- QUERY TASK HISTORY FOR SPECIFIC TIME PERIOD
SELECT *
FROM TABLE (INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START  => TO_TIMESTAMP_LTZ ('SPECIFIED_TIME'),
    SCHEDULED_TIME_RANGE_END    => TO_TIMESTAMP_LTZ ('SPECIFIED_TIME');
    )
);