USE WAREHOUSE COMPUTE_WH;


-- INSPECT DATA WE WISH TO SHARE
SELECT * FROM DEMO_DB.PUBLIC.ORDER_DETAILS;


-- CREATE A SHARE OBJECT
CREATE OR REPLACE SHARE ORDERS_SHARE;


-- SETUP GRANTS
// GRANT USAGE ON DATABASE
GRANT USAGE ON DATABASE DEMO_DB TO SHARE ORDERS_SHARE;

// GRANT USAGE ON SCHEMA
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO SHARE ORDERS_SHARE; 

// GRANT SELECT ON TABLE
GRANT SELECT ON TABLE DEMO_DB.PUBLIC.ORDER_DETAILS TO SHARE ORDERS_SHARE;

// VALIDATE GRANTS
SHOW GRANTS TO SHARE ORDERS_SHARE;


-- ADD CONSUMER ACCOUNT
ALTER SHARE ORDERS_SHARE
    ADD ACCOUNT = <'ACCOUNT-ID'>;


-- ADDITIONAL STEPS IN CONSUMER ACCOUNT
// CREATE A DATABASE & SCHEMA USING SHARE
// CREATE A VIRTUAL WAREHOUSE FOR COMPUTE RESOURCES