-- CREATE USER
CREATE USER TEST_USER
    PASSWORD = 'TEST-USER-PW';


-- GRANT USAGE ON WAREHOUSE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;


-- GRANT PRIVELAGES TO SHARED DATABASE
GRANT IMPORTED PRIVELAGES ON DATABASE DATA_SHARE_DB TO ROLE PUBLIC;