USE WAREHOUSE COMPUTE_WH;


-- CLONE DB
CREATE OR REPLACE DATABASE DEMO_DB_SHARE
    CLONE DEMO_DB;
    

-- CREATE SHARE OBJECT
CREATE OR REPLACE SHARE DB_SHARE;


-- GRANT USAGE ON DATABASE & SCHEMA
GRANT USAGE ON DATABASE DEMO_DB_SHARE TO SHARE COMEPLETE_SCHEMA_SHARE;
GRANT USAGE ON SCHEMA DEMO_DB_SHARE.PUBLIC TO SHARE COMEPLETE_SCHEMA_SHARE;


-- ADD ACCOUNT TO SHARE
ALTER SHARE DB_SHARE
    ADD ACCOUNT = <'ACCOUNT-ID'>