-- TEMPORARY TABLES (CREATE TEMPORARY TABLE)
-- ONLY EXISTS IN CURRENT SESSION (0-1 DAY)
-- TIME TRAVEL RETENTION PERIOD
-- NO FAIL SAFE


USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;


-- CREATE TEMPORARY TABLE
CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.PUBLIC.CUSTOMERS_TEMPORARY (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);


SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_TEMPORARY;


-- SHOW ALL TABLES IN DATABASE
SHOW TABLES;


-- VIEW TABLE METRICS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;


-- CLEAN UP
-- TEMPORARY TABLES ONLY EXISTS WITHIN CURRENT SESSION SO WE DO NOT NEED TO DROP