USE WAREHOUSE COMPUTE_WH;


-- PIPE INFORMATION
DESC PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE;

SHOW PIPES IN DATABASE MANAGE_DB;

SHOW PIPES IN SCHEMA MANAGE_DB.PUBLIC;


-- PAUSE PIPE AND CHECK STATUS
ALTER PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE
    SET PIPE_EXECUTION_PAUSED = TRUE;
    
-- CHECK STATUS OF PAUSED PIPE
SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PUBLIC.EMPLOYEE_PIPE');


-- RESUME PIPE AND CHECK STATUS
ALTER PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE
    SET PIPE_EXECUTION_PAUSED = FALSE;

SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PUBLIC.EMPLOYEE_PIPE');


-- REFRESH PIPE
ALTER PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE REFRESH;