-- SET ROLE
USE ROLE SYSADMIN;


-- CREATE WAREHOUSE
CREATE OR REPLACE WAREHOUSE TEST_WH_SQL 
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 600 -- 10 MIN
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Created w/ SQL'


-- DROP WAREHOUSE
DROP WAREHOUSE TEST_WH_INT