USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS_VALIDATE (
    ORDER_ID    VARCHAR(30),
    AMOUNT      VARCHAR(30),
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(30),
    SUBCATEGORY VARCHAR(30)
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS_VALIDATE;


-- PREPARE STAGE OBJECT
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE_VALIDATE
    URL = 's3://snowflakebucket-copyoption/size/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE_VALIDATE;


-- CREATE AND ALTER FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    SKIP_HEADER = 1;

ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT
    SET SKIP_HEADER = 1;
    

-- SHOW FILE FORMAT PROPERTIES
DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- VALIDATE DATA USING COPY COMMAND AND RETURN_ERRORS (DATA IS NOT LOADED)
COPY INTO DEMO_DB.PUBLIC.ORDERS_VALIDATE
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_VALIDATE
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    FILES = ('Orders.csv', 'Orders2.csv')
    VALIDATION_MODE = RETURN_ERRORS;


-- VALIDATE DATA USING COPY COMMAND AND RETURN N ROWS (DATA IS NOT LOADED)
COPY INTO DEMO_DB.PUBLIC.ORDERS_VALIDATE
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_VALIDATE
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    FILES = ('Orders.csv', 'Orders2.csv')
    VALIDATION_MODE = RETURN_5_ROWS;