USE WAREHOUSE COMPUTE_WH;


-- CREATE PARQUET FILE FORMAT (PARQUET FORMANT NEEDED IN CREATE STAGE STATEMENT)
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.PARQUET_FORMAT
    TYPE = PARQUET;

DESC FILE FORMAT MANAGE_DB.PUBLIC.PARQUET_FORMAT;



-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.PARQUET_STAGE
    URL = 's3://snowflakeparquetdemo'
    FILE_FORMAT = MANAGE_DB.PUBLIC.PARQUET_FORMAT;

LIST @MANAGE_DB.PUBLIC.PARQUET_STAGE;


-- PREVIEW DATA
SELECT * FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE LIMIT 10;


-- PARSE PARQUET DATA
SELECT
    $1:"__index_level_0__",
    $1:"cat_id",
    $1:"d",
    $1:"date",
    $1:"dept_id",
    $1:"id",
    $1:"item_id",
    $1:"state_id",
    $1:"store_id",
    $1:"value"
FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE
LIMIT 10;


-- PARSE WITH CONVERSIONS
SELECT
    $1: "__index_level_0__":: INT AS INDEX_LEVEL,
    $1: "cat_id":: VARCHAR(50) AS CATEGORY,
    DATE ($1: "date":: INT) AS DATE,
    $1: "dept_id":: VARCHAR(50) AS DEPT_ID,
    $1: "id":: VARCHAR(50) AS ID,
    $1: "item_id":: VARCHAR(50) AS ITEM_ID,
    $1: "state_id":: VARCHAR(50) AS STATE_ID,
    $1: "store_id":: VARCHAR(50) AS STORE_ID,
    $1: "value":: INT AS VALUE
FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE
LIMIT 10;


-- ADDING METADATA
SELECT
    $1: "__index_level_0__":: INT AS INDEX_LEVEL,
    $1: "cat_id":: VARCHAR(50) AS CATEGORY,
    DATE ($1: "date":: INT) AS DATE,
    $1: "dept_id":: VARCHAR(50) AS DEPT_ID,
    $1: "id":: VARCHAR(50) AS ID,
    $1: "item_id":: VARCHAR(50) AS ITEM_ID,
    $1: "state_id":: VARCHAR(50) AS STATE_ID,
    $1: "store_id":: VARCHAR(50) AS STORE_ID,
    $1: "value":: INT AS VALUE,
    METADATA$FILENAME AS FILE_NAME,
    METADATA$FILE_ROW_NUMBER AS FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP AS LOAD_DATE,
    TO_TIMESTAMP_NTZ (CURRENT_TIMESTAMP) AS LOAD_DATE_NTZ -- NO TIME ZONE
FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE
LIMIT 10;