USE WAREHOUSE COMPUTE_WH;


-- CREATE DATABASE
CREATE OR REPLACE DATABASE STREAM_DB;


-- CREATE RAW SALES TABLE
CREATE OR REPLACE TABLE STREAM_DB.PUBLIC.SALES_RAW_STAGING (
    ID          VARCHAR,
    PRODUCT     VARCHAR,
    PRICE       VARCHAR,
    AMOUNT      VARCHAR,
    STORE_ID    VARCHAR
);


-- INSERT VALUES SALES
INSERT INTO STREAM_DB.PUBLIC.SALES_RAW_STAGING
    VALUES
        (1,'Banana',1.99,1,1),
        (2,'Lemon',0.99,1,1),
        (3,'Apple',1.79,1,2),
        (4,'Orange Juice',1.89,1,2),
        (5,'Cereals',5.98,2,1);

SELECT * FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING;


-- CREATE STORE TABLE
CREATE OR REPLACE TABLE STREAM_DB.PUBLIC.STORES (
    STORE_ID    NUMBER,
    LOCATION    VARCHAR,
    EMPLOYEES   NUMBER
);


-- INSERT VALUES STORE
INSERT INTO STREAM_DB.PUBLIC.STORES
    VALUES
        (1,'Chicago',33),
        (2,'London',12);

SELECT * FROM STREAM_DB.PUBLIC.STORES;


-- CREATE SALES FINAL TABLE
CREATE OR REPLACE TABLE STREAM_DB.PUBLIC.SALES_FINAL (
    ID          INT,
    PRODUCT     VARCHAR,
    PRICE       NUMBER,
    AMOUNT      INT,
    STORE_ID    INT,
    LOCATION    VARCHAR,
    EMPLOYEES   INT
);


-- INSERT VALUES SALES FINAL
INSERT INTO STREAM_DB.PUBLIC.SALES_FINAL
    SELECT
        R.ID,
        R.PRODUCT,
        R.PRICE,
        R.AMOUNT,
        S.STORE_ID,
        S.LOCATION, 
        S.EMPLOYEES 
    FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING AS R
        JOIN STREAM_DB.PUBLIC.STORES AS S 
            ON R.STORE_ID = S.STORE_ID;

SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;


-- CREATE STREAM OBJECT
CREATE OR REPLACE STREAM SALES_STREAM ON TABLE STREAM_DB.PUBLIC.SALES_RAW_STAGING;

SHOW STREAMS;

DESC STREAM SALES_STREAM;


-- GET CHANGES ON DATA USING STREAMS
SELECT * FROM SALES_STREAM; -- EMPTY
SELECT * FROM SALES_RAW_STAGING;


-- INSERT NEW VALUES
INSERT INTO STREAM_DB.PUBLIC.SALES_RAW_STAGING
    VALUES
        (6,'Mango',1.99,1,2),
        (7,'Garlic',0.99,1,1);


-- GET CHANGES ON DATA USING STREAMS
SELECT * FROM SALES_STREAM; -- CONTAINS NEW RECORDS AND METADATA
SELECT * FROM SALES_RAW_STAGING;
SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;


-- CONSUME STREAM OBJECT
INSERT INTO STREAM_DB.PUBLIC.SALES_FINAL
    SELECT
        R.ID,
        R.PRODUCT,
        R.PRICE,
        R.AMOUNT,
        S.STORE_ID,
        S.LOCATION, 
        S.EMPLOYEES 
    FROM SALES_STREAM AS R
        JOIN STREAM_DB.PUBLIC.STORES AS S 
            ON R.STORE_ID = S.STORE_ID;

SELECT * FROM SALES_STREAM; -- SHOULD NOW BE EMPTY SINCE DATA WAS CONSUMED
SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;