USE WAREHOUSE COMPUTE_WH;


-- INSPECT DATA
SELECT * FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING;
SELECT * FROM SALES_STREAM;


-- UPDATE RECRODS
UPDATE STREAM_DB.PUBLIC.SALES_RAW_STAGING
    SET PRODUCT = 'Potato' WHERE PRODUCT = 'Banana';

SELECT * FROM SALES_STREAM;


-- MERGE DATA
MERGE INTO STREAM_DB.PUBLIC.SALES_FINAL AS F
USING SALES_STREAM AS S
    ON F.ID = S.ID
WHEN MATCHED
    AND S.METADATA$ACTION ='INSERT'
    AND S.METADATA$ISUPDATE ='TRUE'
    THEN UPDATE
        SET F.PRODUCT = S.PRODUCT,
            F.PRICE = S.PRICE,
            F.AMOUNT = S.AMOUNT,
            F.STORE_ID = S.STORE_ID;


-- INSPECT DATA
SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;
SELECT * FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING;     
SELECT * FROM SALES_STREAM;