USE WAREHOUSE COMPUTE_WH;


-- DELETE RECORD
DELETE FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING
WHERE PRODUCT = 'Lemon';


-- INSPECT DATA
SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;
SELECT * FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING;     
SELECT * FROM SALES_STREAM;


-- PROCESS STREAM
MERGE INTO STREAM_DB.PUBLIC.SALES_FINAL AS F
USING SALES_STREAM AS S
    ON F.ID = S.ID
WHEN MATCHED
    AND S.METADATA$ACTION ='DELETE'
    AND S.METADATA$ISUPDATE ='FALSE'
    THEN DELETE;
    
    
-- INSPECT DATA
SELECT * FROM STREAM_DB.PUBLIC.SALES_FINAL;
SELECT * FROM STREAM_DB.PUBLIC.SALES_RAW_STAGING;     
SELECT * FROM SALES_STREAM;