USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDER_PROFIT_FLAG (
    ID          NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ID    VARCHAR(30),
    AMOUNT      INT,
    PROFIT      INT,
    PROFIT_FLAG INT
);

SELECT * FROM DEMO_DB.PUBLIC.ORDER_PROFIT_FLAG;


-- COPY DATA WITH TRANSFORMATION
COPY INTO DEMO_DB.PUBLIC.ORDER_PROFIT_FLAG (ORDER_ID, AMOUNT, PROFIT, PROFIT_FLAG)
    FROM (
        SELECT
            O.$1,
            O.$2,
            O.$3,
            CASE
                WHEN CAST (O.$3 AS INT) <= 0 THEN 0 -- FALSE. NOT PROFITABLE.
                ELSE 1 -- TRUE. PROFITABLE.
            END
        FROM @MANAGE_DB.PUBLIC.AWS_STAGE AS O
    )
    
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
    )
    
    FILES = ('OrderDetails.csv');


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDER_PROFIT_FLAG;