USE WAREHOUSE COMPUTE_WH;


-- CREATE STORED PROCEDURE
CREATE OR REPLACE PROCEDURE CUSTOMERS_INSERT_PROCEDURE (CREATE_DATE VARCHAR)
    RETURNS STRING NOT NULL
    LANGUAGE JAVASCRIPT
    AS
        $$
        var sql_command = 'INSERT INTO TASK_DB.PUBLIC.CUSTOMERS(CREATE_DATE) VALUES(:1);'
        snowflake.execute(
            {
            sqlText: sql_command,
            binds: [CREATE_DATE]
            });
        return "Successfully executed.";
        $$;


-- CREATE TASK
CREATE OR REPLACE TASK CUSTOMER_TASKS_PROCEDURE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    AS CALL CUSTOMERS_INSERT_PROCEDURE (CURRENT_TIMESTAMP);
    
SHOW TASKS;


-- RESUME TASK (DEFAULT IS SUSPENDED)
ALTER TASK CUSTOMER_TAKS_PROCEDURE RESUME;


-- INSPECT DATA
SELECT * FROM TASK_DB.PUBLIC.CUSTOMERS;


-- SUSPEND TASK
ALTER TASK CUSTOMER_TAKS_PROCEDURE SUSPEND;