USE WAREHOUSE COMPUTE_WH;


-- CLONE TABLE (MUST BE PERMANENT OR TRANSIENT TABLE)
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS_CLONE
    CLONE DEMO_DB.PUBLIC.CUSTOMERS; -- INCLUDE TIME TRAVEL SYNTAX IF NEEDED


-- VALIDATE DATA
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_CLONE;


-- UPDATE CLONED TABLE
UPDATE DEMO_DB.PUBLIC.CUSTOMERS_CLONE
    SET LAST_NAME = NULL;
    

-- VALIDATE DATA (ONLY CLONED TABLE WAS UPDATED)
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_CLONE;