USE WAREHOUSE COMPUTE_WH;


-- PREVIEW PARSED PARQUET DATA FROM PRIOR WORKSHEET
SELECT
    $1: "__index_level_0__":: INT AS INDEX_LEVEL,
    $1: "cat_id":: VARCHAR(50) AS CATEGORY,
    DATE ($1: "date":: INT) AS DATE,
    $1: "dept_id":: VARCHAR(50) AS DEPT_ID,
    $1: "id":: VARCHAR(50) AS ID,
    $1: "item_id":: VARCHAR(50) AS ITEM_ID,
    $1: "state_id":: VARCHAR(50) AS STATE_ID,
    $1: "store_id":: VARCHAR(50) AS STORE_ID,
    $1: "value":: INT AS VALUE,
    METADATA$FILENAME AS FILE_NAME,
    METADATA$FILE_ROW_NUMBER AS FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP AS LOAD_DATE,
    TO_TIMESTAMP_NTZ (CURRENT_TIMESTAMP) AS LOAD_DATE_NTZ -- NO TIME ZONE
FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE
LIMIT 10;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.PARQUET_LOAD (
    ROW_NUMBER      INT,
    INDEX_LEVEL     INT,
    CAT_ID          VARCHAR(50),
    DATE            DATE,
    DEPT_ID         VARCHAR(50),
    ID              VARCHAR(50),
    ITEM_ID         VARCHAR(50),
    STATE_ID        VARCHAR(50),
    STORE_ID        VARCHAR(50),
    VALUE           INT,
    LOAD_DATE_NTZ   TIMESTAMP DEFAULT TO_TIMESTAMP_NTZ (CURRENT_TIMESTAMP)
);

INSERT INTO DEMO_DB.PUBLIC.PARQUET_LOAD (
    SELECT
        METADATA$FILE_ROW_NUMBER,    
        $1: "__index_level_0__":: INT,
        $1: "cat_id":: VARCHAR(50),
        DATE ($1: "date":: INT),
        $1: "dept_id":: VARCHAR(50),
        $1: "id":: VARCHAR(50),
        $1: "item_id":: VARCHAR(50),
        $1: "state_id":: VARCHAR(50),
        $1: "store_id":: VARCHAR(50),
        $1: "value":: INT,
        TO_TIMESTAMP_NTZ (CURRENT_TIMESTAMP)
    FROM @MANAGE_DB.PUBLIC.PARQUET_STAGE
);


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.PARQUET_LOAD LIMIT 10;