# train-project/pyproject.toml
[build-system]
requires = ["setuptools>=51.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 66

[tool.isort]
profile = 'black'
line_length = 66
