-- SET ROLE
USE ROLE SYS ADMIN;


-- CREATE WAREHOUSE
CREATE OR REPLACE WAREHOUSE COMPUTE_WH
    WAREHOUSE_SIZE = SMALL
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE
    COMMENT = 'VIRTUAL WAREHOUSE CREATED W/ SQL STATEMENT'