-- CREATE DATABASE
CREATE OR REPLACE DATABASE EXERCISE_DB;


-- CREATE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS (
    CUSTOMER    INT,
    FIRST_NAME  VARCHAR,
    LAST_NAME   VARCHAR,
    EMAIL       VARCHAR,
    AGE         INT,
    CITY        VARCHAR
);

SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- LOAD DATA
COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
    FROM 's3://snowflake-assignments-mc/gettingstarted/customers.csv'
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
    );


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;