USE WAREHOUSE COMPUTE_WH;


-- INSPECT TABLE
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- CREATE STAGE OBJECT
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE
    URL = 's3://snowflake-assignments-mc/loadingdata/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE;


-- LOAD DATA
COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE
    FILES = ('customers2.csv', 'customers3.csv')
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ';'
        SKIP_HEADER = 1
    );


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- CLEAN UP
DROP TABLE IF EXISTS EXERCISE_DB.PUBLIC.CUSTOMERS;