-- INSPECT TABLE
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- CREATE STAGE OBJECT
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_CUSTOMERS
    URL = 's3://snowflake-assignments-mc/fileformat/';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_CUSTOMERS;


-- CREATE AND ALTER FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT;

ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT
    SET FIELD_DELIMITER = '|';

ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT
    SET SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT;


-- LOAD DATA USING FILE FORMAT OBJECT
COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_CUSTOMERS
    FILES = ('customers4.csv')
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.CSV_FORMAT;


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;