USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.EMPLOYEES (
    CUSTOMER_ID INT,
    FIRST_NAME  VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    EMAIL       VARCHAR(50),
    AGE         INT,
    DEPARTMENT  VARCHAR(50)
);

SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE
    URL = 's3://snowflake-assignments-mc/copyoptions/example2/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE;


-- CREATE AND ALTER FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    SKIP_HEADER = 1;
    
DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- USE COPY OPTION TO VALIDATE FOR ERRORS (RETURN ERRORS)
COPY INTO EXERCISE_DB.PUBLIC.EMPLOYEES
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    FILES = ('employees_error.csv')
    VALIDATION_MODE = RETURN_ERRORS;


-- ADD COPY OPTION TO TRUNCATE COLUMN AND AVOID ERROR
COPY INTO EXERCISE_DB.PUBLIC.EMPLOYEES
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    FILES = ('employees_error.csv')
    TRUNCATECOLUMNS = TRUE;


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES;


-- CLEAN UP
DROP TABLE IF EXISTS EXERCISE_DB.PUBLIC.EMPLOYEES;