USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.TIME_TRAVEL_SAMPLE
    AS (
        SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PART"
    );
 
SELECT * 
FROM EXERCISE_DB.PUBLIC.TIME_TRAVEL_SAMPLE
ORDER BY P_MFGR DESC;


-- UPDATE THE TABLE
UPDATE EXERCISE_DB.PUBLIC.TIME_TRAVEL_SAMPLE
    SET P_MFGR='Manufacturer#CompanyX'
    WHERE P_MFGR='Manufacturer#5';

SELECT * 
FROM EXERCISE_DB.PUBLIC.TIME_TRAVEL_SAMPLE
ORDER BY P_MFGR DESC;


-- TIME TRAVEL W/ QUERY ID
SELECT * FROM EXERCISE_DB.PUBLIC.TIME_TRAVEL_SAMPLE BEFORE (STATEMENT => '01a7a1b6-0004-2d8f-002c-c8070004d14a');