USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS (
    ORDER_ID    VARCHAR(30),
    AMOUNT      VARCHAR(30),
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(30),
    SUBCATEGORY VARCHAR(30)
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    URL = 's3://snowflakebucket-copyoption/returnfailed/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS;


-- LOAD DATA AND RETURN DETAILS FOR FAILED FILES ONLY
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*'
    ON_ERROR = CONTINUE
    RETURN_FAILED_ONLY = TRUE; -- DEFAULT FALSE: RETURNS DETAILES FOR ALL FILES


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDERS;