USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS (
    ORDER_ID    VARCHAR(30),
    AMOUNT      VARCHAR(30),
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(30),
    SUBCATEGORY VARCHAR(30)
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    URL = 's3://snowflakebucket-copyoption/size/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*';

SELECT * FROM DEMO_DB.PUBLIC.ORDERS; -- 3,000 ROWS


-- ATTEMPT TO RE-LOAD DATA (COPY WILL NOT PROCESS ALREADY LOADED FILES)
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*';


-- RE-LOAD DATA USING COPY OPTION FORCE
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*'
    FORCE = TRUE; 
    -- BE MINDFUL OF DUPLICATION. THIS MAY BE AN OPTION APPLICABLE TO SPECIFIC A USE CASE.


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDERS; -- NOW 6,000 ROWS. ALL RECORDS HAVE BEEN DUPLICATED DUE TO FORCE OPTION.