USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS (
    ORDER_ID    VARCHAR(30),
    AMOUNT      VARCHAR(30),
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(10), -- SET TO 10 FOR DEMO
    SUBCATEGORY VARCHAR(30)
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    URL = 's3://snowflakebucket-copyoption/size/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS;


-- LOAD DATA (CATEGORY COLUMN WILL CAUSE AN ERROR DUE TO SIZE LIMIT)
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*';


-- LOAD DATA AND TRUNCATE COLUMNS TO PREVENT ERROR IN ABOVE SITUATION
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT
    PATTERN = '.*Order.*'
    TRUNCATECOLUMNS = TRUE; -- DEFAULT: FALSE


-- INSEPCT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDERS;