USE WAREHOUSE COMPUTE_WH;


-- QUERY LOAD HISTORY (DB SPECIFIC)
SELECT * FROM DEMO_DB.INFORMATION_SCHEMA.LOAD_HISTORY;


-- QUERY LOAD HISTORT FROM GLOBAL DB
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY;


-- QUERYING SPECIFIC TABLES/SCHEMA FROM GLOBAL LOAD HISTORY
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY
WHERE
    SCHEMA_NAME = 'PUBLIC'
    AND TABLE_NAME = 'ORDER_DETAILS_ERRORS';


SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY
WHERE
    SCHEMA_NAME = 'PUBLIC'
    AND TABLE_NAME = 'ORDER_DETAILS_ERRORS'
    AND ERROR_COUNT > 0;


SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY
WHERE DATE (LAST_LOAD_TIME) <= DATEADD (DAYS, -1, CURRENT_DATE); -- RETURNS LOADS PRIOR TO TODAY