-- CREATE DATABASE TO STORE DATA
CREATE OR REPLACE DATABASE DEMO_DB;

-- CREATE DATABASE TO MANAGE STAGE OBJECTS
CREATE OR REPLACE DATABASE MANAGE_DB;
CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;


-- CREATE EXTERNAL STAGE
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
    URL = 's3://bucketsnowflakes3' 
    -- OPEN BUCKET. NO CREDENTIALS NEEDED.


-- LIST FILES IN STAGE
LIST @AWS_STAGE;


-- EXTERNAL STAGE DESCRIPTION
DESC STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;