-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDER_DETAILS (
    ORDER_ID    VARCHAR(30),
    AMOUNT      INT,
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(30),
    SUBCATEGORY VARCHAR(30)
);


-- INSPECT NEW TABLE
SELECT * FROM DEMO_DB.PUBLIC.ORDER_DETAILS;


-- INSPECT STAGE (CREATED PRIOR NOTEBOOK)
LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE;


-- LOAD DATA FROM S3 BUCKET
COPY INTO DEMO_DB.PUBLIC.ORDER_DETAILS
    FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
    FILES = ('OrderDetails.csv')
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
    );


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDER_DETAILS;