-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- CREATE EXTERNAL STAGE
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.CUSTOMER_STAGE
    URL = 's3://snowflake-assignments-mc/loadingdata/';
    -- OPEN BUCKET. NO CREDENTIALS NEEDED.

LIST @MANAGE_DB.EXTERNAL_STAGES.CUSTOMER_STAGE;


-- LOAD DATA FROM S3 BUCKET
COPY INTO DEMO_DB.PUBLIC.CUSTOMERS
    FROM @CUSTOMER_STAGE
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ';'
        SKIP_HEADER = 1
    )
    FILES = ('customers2.csv', 'customers3.csv');


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;