USE WAREHOUSE COMPUTE_WH;

-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS (
    ORDER_ID    VARCHAR(30),
    AMOUNT      VARCHAR(30),
    PROFIT      INT,
    QUANTITY    INT,
    CATEGORY    VARCHAR(30),
    SUBCATEGORY VARCHAR(30)
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ORDERS
    URL = 's3://snowflakebucket-copyoption/size/';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ORDERS;


-- LOAD DATA WITH SIZE LIMIT (WILL ONLY LOAD FIRST FILE IN THIS CASE)
COPY INTO DEMO_DB.PUBLIC.ORDERS
    FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ORDERS
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.CSV_FORMAT
    PATTERN = '.*Order.*'
    SIZE_LIMIT = 54600;


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.ORDERS;