-- PERMANENT TABLES (CREATE TABLE)
-- TIME TRAVEL RETENTION PERIOD (0-90 DAYS)
-- FAIL SAFE


USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;


-- CREATE PERMANENT TABLE (PERMANENT TABLES ARE NOT TRANSIENT)
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS_PERMANENT (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);


-- SHOW ALL TABLES IN DATABASE
SHOW TABLES;


-- VIEW TABLE METRICS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;


-- CLEAN UP
DROP TABLE IF EXISTS DEMO_DB.PUBLIC.CUSTOMERS_PERMANENT;