import openai


class ChatBot:
    """
    A class representing a chatbot powered by OpenAI's GPT-3.5 model.
    """
    
    def __init__(self):
        """
        Initializes the ChatBot instance.
        """

        openai.api_key = ''

    def get_response(self, user_input):
        """
        Generate a response from the chatbot given a user input.

        Args:
            user_input (str): The input provided by the user.

        Returns:
            str: The response generated by the chatbot.
        """

        response = openai.Completion.create(
            engine='gpt-3.5-turbo-0125',
            prompt=user_input,
            max_tokens=3000,
            temperature=0.5
        ).choices[0].text

        return response


if __name__ == '__main__':

    # create chatbot instance
    chatbot = ChatBot()

    # get response and print
    response = chatbot.get_response('')
    print(response)