USE WAREHOUSE COMPUTE_WH;

-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    URL = 's3://data-snowflake-fundamentals/time-travel/'
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    FILES = ('customers.csv');

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- ACCIDENTAL UPDATE
UPDATE DEMO_DB.PUBLIC.CUSTOMERS
    SET FIRST_NAME = 'Joyen';

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- TIME TRAVEL METHOD 1: LOOK BACK SPECIFIED TIME (OFFSET IN SECONDS)
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS AT (OFFSET => -60);


-- TIME TRAVEL METHOD 2: LOOK BACK SPECIFIED TIME STAMP
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS BEFORE (TIMESTAMP => '2022-10-14 22:35:00.000'::TIMESTAMP);


-- TIME TRAVEL METHOD 3: LOOK BACK TO SPECIFIED QUERY ID
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS BEFORE (STATEMENT => '01a7a1aa-0004-2e0c-002c-c8070006205a');