USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    URL = 's3://data-snowflake-fundamentals/time-travel/'
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    FILES = ('customers.csv');

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS; -- QUERY ID: 01a7a61f-0004-2e63-002c-c8070005d092


-- ACCIDENTAL UPDATE
UPDATE DEMO_DB.PUBLIC.CUSTOMERS
    SET LAST_NAME = 'Tyson';

UPDATE DEMO_DB.PUBLIC.CUSTOMERS
    SET JOB = 'Data Analyst';

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS; -- QUERY ID: 01a7a621-0004-2e42-002c-c80700066022


-- INSPECT ORIGINAL DATA LOAD
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS BEFORE (STATEMENT => '01a7a61f-0004-2e63-002c-c8070005d092');


-- RESTORE DATA TO BACKUP TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS_BACKUP AS (
    SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS BEFORE (STATEMENT => '01a7a61f-0004-2e63-002c-c8070005d092')
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_BACKUP;


-- TRUNCATE ORIGINAL TABLE
-- IF WE RE-CREATE THE TABLE, WE LOSE METADATA (BEST PRACTICE IS TO TRUNCATE AND INSERT BACKUP)
TRUNCATE DEMO_DB.PUBLIC.CUSTOMERS;

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- RELOAD DATA USING TIME TRAVEL BACKUO
INSERT INTO DEMO_DB.PUBLIC.CUSTOMERS
    SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_BACKUP;

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;