USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    URL = 's3://data-snowflake-fundamentals/time-travel/'
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.PUBLIC.TIME_TRAVEL_STAGE
    FILES = ('customers.csv');

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- ACCIDENTAL DROP AND UNDROP (TABLES)
DROP TABLE DEMO_DB.PUBLIC.CUSTOMERS;

UNDROP TABLE DEMO_DB.PUBLIC.CUSTOMERS;

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- ACCIDENTAL DROP AND UNDROP (SCHEMAS)
DROP SCHEMA DEMO_DB.PUBLIC; -- ALL TABLES IN SCHEMA WILL ALSO BE DROPPED

UNDROP SCHEMA DEMO_DB.PUBLIC; -- RESTORES UNDERLINING TABLES

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- ACCIDENTAL DROP AND UNDROP (DATABASE)
DROP DATABASE DEMO_DB;

UNDROP DATABASE DEMO_DB; -- RESTORES WITH ALL SCHEMAS AND TABLES