USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;


-- SHOW TABLE METADATA (DEFAULT RETENTION TIME = 1 DAY)
SHOW TABLES  LIKE 'CUSTOMERS';


-- ALTER TABLE TO EXTEND RETENTION TIME (EXTENDED RETENTION TIME WILL INCREASE COSTS DUE TO INCREASED STORAGE)
ALTER TABLE DEMO_DB.PUBLIC.CUSTOMERS
    SET DATA_RETENTION_TIME_IN_DAYS = 2;

SHOW TABLES  LIKE 'CUSTOMERS';


-- QUERY STORAGE USAGE (SEE INCREASED TIME TRAVEL BYTES FOR ABOVE TABLE)
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;