USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DEMO_DB.PUBLIC;


-- CREATE TABLE 
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS_MASK (
    ID              NUMBER,
    FULL_NAME       VARCHAR,
    EMAIL           VARCHAR,
    PHONE           VARCHAR,
    SPENT           NUMBER,
    CREATED_DATE    DATE DEFAULT CURRENT_DATE
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_MASK;


-- INSERT VALUES
INSERT INTO DEMO_DB.PUBLIC.CUSTOMERS_MASK (ID, FULL_NAME, EMAIL, PHONE, SPENT)
    VALUES
      (1,'Lewiss MacDwyer','lmacdwyer0@un.org','262-665-9168',140),
      (2,'Ty Pettingall','tpettingall1@mayoclinic.com','734-987-7120',254),
      (3,'Marlee Spadazzi','mspadazzi2@txnews.com','867-946-3659',120),
      (4,'Heywood Tearney','htearney3@patch.com','563-853-8192',1230),
      (5,'Odilia Seti','oseti4@globo.com','730-451-8637',143),
      (6,'Meggie Washtell','mwashtell5@rediff.com','568-896-6138',600);


-- CREATE ROLES
CREATE OR REPLACE ROLE ANALYST_MASKED;
CREATE OR REPLACE ROLE ANALYST_FULL;


-- GRANT SELECT ON TABLE TO ROLES
GRANT SELECT ON TABLE DEMO_DB.PUBLIC.CUSTOMERS_MASK TO ROLE ANALYST_MASKED;
GRANT SELECT ON TABLE DEMO_DB.PUBLIC.CUSTOMERS_MASK TO ROLE ANALYST_FULL;


-- GRANT DATABASE ACCESS TO ROLES
GRANT USAGE ON DATABASE DEMO_DB TO ROLE ANALYST_MASKED;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE ANALYST_FULL;


-- GRANT SCHEMA ACCESS TO ROLES
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE ANALYST_MASKED;
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE ANALYST_FULL;


-- GRANT WAREHOUSE ACCESS TO ROLES
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_MASKED;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_FULL;


-- ASSIGN ROLES TO A USER
GRANT ROLE ANALYST_MASKED TO USER NAREYES;
GRANT ROLE ANALYST_FULL TO USER NAREYES;


-- SET UP MASKING POLICY
CREATE OR REPLACE MASKING POLICY DEMO_DB.PUBLIC.PHONE
    AS (VAL VARCHAR) RETURNS VARCHAR ->
        CASE
            WHEN CURRENT_ROLE() IN ('ANALYST_FULL', 'ACCOUNTADMIN') THEN VAL
            ELSE '###-###-###'
        END;


-- APPLY POLICY ON SPECIFIC COLUMN
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.CUSTOMERS_MASK
    MODIFY COLUMN PHONE
    SET MASKING POLICY DEMO_DB.PUBLIC.PHONE;


-- VALIDATE POLICIES
USE ROLE ANALYST_FULL;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_MASK;

USE ROLE ANALYST_MASKED;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_MASK;