USE WAREHOUSE COMPUTE_WH;


-- ALTER EXISITING POLICY
ALTER MASKING POLICY DEMO_DB.PUBLIC.PHONE
    SET BODY ->
        CASE
            WHEN CURRENT_ROLE() IN ('ANALYST_FULL', 'ACCOUNTADMIN') THEN VAL
            ELSE '###-###-####'
        END;


-- LIST POLICIES
DESC MASKING POLICY DEMO_DB.PUBLIC.PHONE;
SHOW MASKING POLICIES;


-- VALIDATE POLICIES
USE ROLE ANALYST_FULL;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_MASK;

USE ROLE ANALYST_MASKED;
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS_MASK;