USE WAREHOUSE COMPUTE_WH;

-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS (
    ID          INT,
    FIRST_NAME  VARCHAR,
    LAST_NAME   VARCHAR,
    EMAIL       VARCHAR,
    AGE         INT,
    CITY        VARCHAR
);

SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;


-- LOAD DATA FROM S3 BUCKET
COPY INTO DEMO_DB.PUBLIC.CUSTOMERS
    FROM s3://snowflake-assignments-mc/gettingstarted/customers.csv
    FILE_FORMAT = (
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1 -- TRUE
    );


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMERS;