USE WAREHOUSE COMPUTE_WH;


-- CREATE TASK WITH CRON SCHEDULER
CREATE OR REPLACE TASK CUSTOMER_INSERT_CRON
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 7,10 * * 5L UTC'
    AS 
        INSERT INTO CUSTOMERS (CREATED_DATE) 
        VALUES (CURRENT_TIMESTAMP); -- DEFAULT STATE IS SUSPENDED

SHOW TASKS;


/*
-- CRON SCHEDULING
-- MINUTE (0-59)
-- HOUR (0-23)
-- DAY OF MONTH (1-31, or L)
-- MONTH (1-12, JAN-DEC)
-- DAY OF WEEK (0-6, SUN-SAT, or L)
-- L = LAST DAY

-- CRON SCHEDULING EXAMPLES
// EVERY MINUTE
// SCHEDULE = 'USING CRON * * * * * UTC'


// EVERY DAY AT 6AM UTC
// SCHEDULE = 'USING CRON 0 6 * * * UTC'

// EVERY HOUR STARTING AT 9 AM AND ENDING AT 5 PM ON SUNDAYS 
// SCHEDULE = 'USING CRON 0 9-17 * * SUN America/Los_Angeles'
*/