-- CREATE STORAGE INTEGRATION OBJECT
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::929339109708:role/snowflake-access-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://s3snowflakestorage/csv', 's3://s3snowflakestorage/json')
        COMMENT = 'OPTIONAL COMMENT';


-- INSPECT STORAGE INTEGRATION PROPERTIES
DESC INTEGRATION S3_INT;