USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.MOVIE_TITLES (
    SHOW_ID         STRING,
    TYPE            STRING,
    TITLE           STRING,
    DIRECTOR        STRING,
    CAST            STRING,
    COUNTRY         STRING,
    DATE_ADDED      STRING,
    RELEASE_YEAR    STRING,
    RATING          STRING,
    DURATION        STRING,
    LISTED_IN       STRING,
    DESCRIPTION     STRING
);

SELECT * FROM DEMO_DB.PUBLIC.MOVIE_TITLES;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.NETFLIX_STAGE
    URL = 's3://s3snowflakestorage/csv/'
    STORAGE_INTEGRATION = S3_INT
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.NETFLIX_STAGE;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.MOVIE_TITLES
    FROM @MANAGE_DB.PUBLIC.NETFLIX_STAGE
    FILES = ('netflix_titles.csv');


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.MOVIE_TITLES;