USE WAREHOUSE COMPUTE_WH;


-- CLEAR CACHE FOR TESTING
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER WAREHOUSE COMPUTE_WH SUSPEND;
ALTER WAREHOUSE COMPUTE_WH RESUME;


-- EXAMPLE QUERY (LARGE DATASET) (EXECUTION TIME: 5.3 SEC)
SELECT
    YEAR (O_ORDERDATE)  AS YEAR,
    MAX (O_COMMENT)     AS MAX_COMMENT,
    MIN (O_COMMENT)     AS MIN_COMMENT,
    MAX (O_CLERK)       AS MAX_CLERK,
    MIN (O_CLERK)       AS MIN_CLERK
FROM DEMO_DB.PUBLIC.ORDERS
GROUP BY YEAR(O_ORDERDATE)
ORDER BY YEAR(O_ORDERDATE);


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS as (
    SELECT * 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS; -- (EXECUTION TIME: 50 SEC)


-- CREATE MATERIALIZED VIEW
CREATE OR REPLACE MATERIALIZED VIEW DEMO_DB.PUBLIC.ORDERS_MV AS (
    SELECT
        YEAR (O_ORDERDATE)  AS YEAR,
        MAX (O_COMMENT)     AS MAX_COMMENT,
        MIN (O_COMMENT)     AS MIN_COMMENT,
        MAX (O_CLERK)       AS MAX_CLERK,
        MIN (O_CLERK)       AS MIN_CLERK
    FROM DEMO_DB.PUBLIC.ORDERS
    GROUP BY YEAR(O_ORDERDATE)
);


-- INSPECT DATA (EXECUTION TIME: 1.3 SEC)
-- CHANGES TO UNDERLINING DATA WILL REFLECT IN VIEW
SELECT * FROM DEMO_DB.PUBLIC.ORDERS_MV;


-- SHOW MATERIALIZED VIEWS
SHOW MATERIALIZED VIEWS;


-- INSPECT CREDITS USED
SELECT *
FROM TABLE (DEMO_DB.INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY());