USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS as (
    SELECT * 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
);

SELECT * FROM DEMO_DB.PUBLIC.ORDERS;


-- EXAMPLE STATEMENT VIEW (LARGE DATASET)
SELECT
    YEAR (O_ORDERDATE)  AS YEAR,
    MAX (O_COMMENT)     AS MAX_COMMENT,
    MIN (O_COMMENT)     AS MIN_COMMENT,
    MAX (O_CLERK)       AS MAX_CLERK,
    MIN (O_CLERK)       AS MIN_CLERK
FROM DEMO_DB.PUBLIC.ORDERS
GROUP BY YEAR(O_ORDERDATE)
ORDER BY YEAR(O_ORDERDATE);


-- CREATE MATERIALIZED VIEW
CREATE OR REPLACE MATERIALIZED VIEW DEMO_DB.PUBLIC.ORDERS_MV AS (
    SELECT
        YEAR (O_ORDERDATE)  AS YEAR,
        MAX (O_COMMENT)     AS MAX_COMMENT,
        MIN (O_COMMENT)     AS MIN_COMMENT,
        MAX (O_CLERK)       AS MAX_CLERK,
        MIN (O_CLERK)       AS MIN_CLERK
    FROM DEMO_DB.PUBLIC.ORDERS
    GROUP BY YEAR(O_ORDERDATE)
);


-- INSPECT DATA
-- CHANGES TO UNDERLINING DATA WILL REFLECT IN VIEW
SELECT * FROM DEMO_DB.PUBLIC.ORDERS_MV;


-- SHOW MATERIALIZED VIEWS
SHOW MATERIALIZED VIEWS;


-- INSPECT CREDITS USED
SELECT *
FROM TABLE (DEMO_DB.INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY());