-- TRANSIENT TABLES (CREATE TRANSIENT TABLE)
-- TIME TRAVEL RETENTION PERIOD (0-1 DAY)
-- NO FAIL SAFE


USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;


-- CREATE TRANSIENT TABLE
CREATE OR REPLACE TRANSIENT TABLE DEMO_DB.PUBLIC.CUSTOMERS_TRANSIENT (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    GENDER      STRING,
    JOB         STRING,
    PHONE       STRING
);


-- SHOW ALL TABLES IN DATABASE
SHOW TABLES;


-- VIEW TABLE METRICS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;


-- CLEAN UP
DROP TABLE IF EXISTS DEMO_DB.PUBLIC.CUSTOMERS_TRANSIENT;