USE WAREHOUSE COMPUTE_WH;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.SNOWPIPE_STAGE
    URL = 's3://s3snowflakestorage/csv/'
    STORAGE_INTEGRATION = S3_INT
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.SNOWPIPE_STAGE;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.EMPLOYEES (
    ID          INT,
    FIRST_NAME  STRING,
    LAST_NAME   STRING,
    EMAIL       STRING,
    LOCATION    STRING,
    DEPARTMENT  STRING
);

SELECT * FROM DEMO_DB.PUBLIC.EMPLOYEES;


-- CREATE PIPE
CREATE OR REPLACE PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE
    AUTO_INGEST = TRUE
AS
    COPY INTO DEMO_DB.PUBLIC.EMPLOYEES
    FROM @MANAGE_DB.PUBLIC.SNOWPIPE_STAGE;

DESC PIPE MANAGE_DB.PUBLIC.EMPLOYEE_PIPE; -- COPY NOTIFICATION CHANNEL AND UPDATE EVENT NOTIFICATION IN AWS


-- INSPECT DATA (DATA SHOULD LOAD 30-60SEC AFTER UPLOADED IN S3 BUCKET)
SELECT * FROM DEMO_DB.PUBLIC.EMPLOYEES;