USE WAREHOUSE COMPUTE_WH;


-- VALIDATE PIPE
SELECT SYSTEM$PIPE_STATUS('MANAGE_DB.PUBLIC.EMPLOYEE_PIPE');


-- RETRIEVE ERROR MESSAGE
SELECT * FROM TABLE (
    VALIDATE_PIPE_LOAD (
        PIPE_NAME => 'MANAGE_DB.PUBLIC.EMPLOYEE_PIPE',
        START_TIME => DATEADD (HOUR, -2, CURRENT_TIMESTAMP())
    )
);


-- RETRIEVE COMMAND HISTORY
SELECT * FROM TABLE (
    MANAGE_DB.INFORMATION_SCHEMA.COPY_HISTORY (
        TABLE_NAME => 'MANAGE_DB.PUBLIC.EMPLOYEE_PIPE',
        START_TIME => DATEADD (HOUR, -2, CURRENT_TIMESTAMP())
    )
);