-- CREATE STORAGE INTEGRATION OBJECT
CREATE OR REPLACE STORAGE INTEGRATION AZURE_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = AZURE
    ENABLED = TRUE
    AZURE_TENANT_ID = '0fe4b9fa-15d9-4f96-b5a7-2aa5febd7c86'
    STORAGE_ALLOWED_LOCATIONS = ('azure://snowflakestoracct.blob.core.windows.net/csv', 'azure://snowflakestoracct.blob.core.windows.net/json')
        COMMENT = 'OPTIONAL COMMENT';


-- INSPECT STORAGE INTEGRATION PROPERTIES
DESC STORAGE INTEGRATION AZURE_INT;