USE WAREHOUSE COMPUTE_WH;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AZURE_STAGE
    URL = 'azure://snowflakestoracct.blob.core.windows.net/csv/'
    STORAGE_INTEGRATION = AZURE_INT
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;

LIST @MANAGE_DB.PUBLIC.AZURE_STAGE;


-- QUERY DATA FROM STAGE
SELECT 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
FROM @MANAGE_DB.PUBLIC.AZURE_STAGE;


-- CREATE TABLE
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.HAPPINESS_2021 (
    COUNTRY_NAME                                VARCHAR,
    REGIONAL_INDICATOR                          VARCHAR,
    LADDER_SCORE                                NUMBER(4,3),
    STANDARD_ERROR                              NUMBER(4,3),
    UPPER_WHISKER                               NUMBER(4,3),
    LOWER_WHISKER                               NUMBER(4,3),
    LOGGED_GDP                                  NUMBER(5,3),
    SOCIAL_SUPPORT                              NUMBER(4,3),
    HEALTHY_LIFE_EXPECTANCY                     NUMBER(5,3),
    FREEDOM_TO_MAKE_LIFE_CHOICES                NUMBER(4,3),
    GENEROSITY                                  NUMBER(4,3),
    PERCEPTIONS_OF_CORRUPTION                   NUMBER(4,3),
    LADDER_SCORE_IN_DYSTOPIA                    NUMBER(4,3),
    EXPLAINED_BY_LOG_GDP_PER_CAPITA             NUMBER(4,3),
    EXPLAINED_BY_SOCIAL_SUPPORT                 NUMBER(4,3),
    EXPLAINED_BY_HEALTHY_LIFE_EXPECTANCY        NUMBER(4,3),
    EXPLAINED_BY_FREEDOM_TO_MAKE_LIFE_CHOICES   NUMBER(4,3),
    EXPLAINED_BY_GENEROSITY                     NUMBER(4,3),
    EXPLAINED_BY_PERCEPTIONS_OF_CORRUPTION      NUMBER(4,3),
    DYSTOPIA_RESULT                           NUMBER(4,3)
);

SELECT * FROM DEMO_DB.PUBLIC.HAPPINESS_2021;


-- LOAD DATA
COPY INTO DEMO_DB.PUBLIC.HAPPINESS_2021
    FROM @MANAGE_DB.PUBLIC.AZURE_STAGE
    FILES = ('world_happiness_report_2021.csv');


-- INSPECT DATA
SELECT * FROM DEMO_DB.PUBLIC.MOVIE_TITLES;