USE WAREHOUSE COMPUTE_WH;


-- INSPECT TABLE
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- CREATE STAGE OBJECT
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.AWS_STAGE
    URL = 's3://snowflake-assignments-mc/fileformat/';

LIST @MANAGE_DB.PUBLIC.AWS_STAGE;


-- CREATE AND ALTER FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT
    FIELD_DELIMITER = '|'
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.PUBLIC.CSV_FORMAT;


-- LOAD DATA USING FILE FORMAT OBJECT
COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.PUBLIC.AWS_STAGE
    FILES = ('customers4.csv')
    FILE_FORMAT = MANAGE_DB.PUBLIC.CSV_FORMAT;


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;


-- CLEAN UP
DROP TABLE IF EXISTS EXERCISE_DB.PUBLIC.CUSTOMERS;