USE WAREHOUSE COMPUTE_WH;


-- CREATE STAGE
CREATE OR REPLACE STAGE MANAGE_DB.PUBLIC.JSON_STAGE
    URL = 's3://snowflake-assignments-mc/unstructureddata/';

LIST @MANAGE_DB.PUBLIC.JSON_STAGE;


-- CREATE FILE FORMAT OBJECT
CREATE OR REPLACE FILE FORMAT MANAGE_DB.PUBLIC.JSON_FORMAT
    TYPE = JSON;

DESC FILE FORMAT MANAGE_DB.PUBLIC.JSON_FORMAT;


-- CREATE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS (
    RAW_FILE    VARIANT
);

SELECT * FROM EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS;


-- COPY JSON DATA
COPY INTO EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS
    FROM @MANAGE_DB.PUBLIC.JSON_STAGE
    FILE_FORMAT = MANAGE_DB.PUBLIC.JSON_FORMAT
    FILES = ('Jobskills.json');


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS;


-- PARSE JSON DATA
SELECT
    RAW_FILE: first_name:: STRING AS FIRST_NAME,
    RAW_FILE: last_name:: STRING AS LAST_NAME,
    RAW_FILE: Skills[0]:: STRING AS SKILLS_1,
    RAW_FILE: Skills[1]:: STRING AS SKILLS_2,
    RAW_FILE: Skills[2]:: STRING AS SKILLS_2
FROM EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS;


-- CREATE TABLE AND INSERT PARSED DATA
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.JOBSKILLS_PARSED (
    FIRST_NAME  VARCHAR(30),
    LAST_NAME   VARCHAR(30),
    SKILLS_1    VARCHAR(50),
    SKILLS_2    VARCHAR(50),
    SKILLS_3    VARCHAR(50)
) 

AS (
SELECT
    RAW_FILE: first_name:: STRING,
    RAW_FILE: last_name:: STRING,
    RAW_FILE: Skills[0]:: STRING,
    RAW_FILE: Skills[1]:: STRING,
    RAW_FILE: Skills[2]:: STRING
FROM EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS
);


-- INSPECT DATA
SELECT * FROM EXERCISE_DB.PUBLIC.JOBSKILLS_PARSED;


-- CLEAN UP
DROP TABLE IF EXISTS EXERCISE_DB.PUBLIC.JSON_RAW_JOBSKILLS;
DROP TABLE IF EXISTS EXERCISE_DB.PUBLIC.JOBSKILLS_PARSED;