USE WAREHOUSE COMPUTE_WH;


-- CREATE DATABASE AND SCHEMA
CREATE DATABASE TIME_TRAVEL_EXERCISE;
CREATE SCHEMA TIME_TRAVEL_EXERCISE.COMPANY_X;


-- CREATE TABLE AND LOAD
CREATE TABLE TIME_TRAVEL_EXERCISE.COMPANY_X.CUSTOMERS AS (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
);

SELECT * FROM TIME_TRAVEL_EXERCISE.COMPANY_X.CUSTOMERS;


-- ACCIDENTAL SCHEMA DROP
DROP SCHEMA TIME_TRAVEL_EXERCISE.COMPANY_X;


-- UNDROP SCEHMA
UNDROP SCHEMA TIME_TRAVEL_EXERCISE.COMPANY_X;


-- INSPECT DATA
SELECT * FROM TIME_TRAVEL_EXERCISE.COMPANY_X.CUSTOMERS;