USE WAREHOUSE COMPUTE_WH;


-- CREATE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.SUPPLIER AS (
    SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER"
);

SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER;


-- CLONE TABLE
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.SUPPLIER_CLONE
    CLONE EXERCISE_DB.PUBLIC.SUPPLIER;


-- VALIDATE DATA
SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER;
SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER_CLONE;


-- UPDATE CLONE TABLE
UPDATE EXERCISE_DB.PUBLIC.SUPPLIER_CLONE
    SET S_PHONE = '###'; -- QUERY_ID: '01a7b0e4-0004-2e96-002c-c80700077052'

SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER_CLONE;


-- CLONE TABLE USING TIME TRAVEL
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.SUPPLIER_CLONE_TT
    CLONE EXERCISE_DB.PUBLIC.SUPPLIER_CLONE BEFORE (STATEMENT => '01a7b0e4-0004-2e96-002c-c80700077052');


-- VALIDATE DATA
SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER_CLONE; -- MODIFIED TABLE
SELECT * FROM EXERCISE_DB.PUBLIC.SUPPLIER_CLONE_TT; -- RESTORED TABLE