USE WAREHOUSE COMPUTE_WH;


-- SAMPLE QUERY (EXECUTION TIME: 4.4S)
SELECT 
    AVG(PS_SUPPLYCOST)  AS PS_SUPPLYCOST_AVG,
    AVG(PS_AVAILQTY)    AS PS_AVAILQTY_AVG,
    MAX(PS_COMMENT)     AS PS_COMMENT_MAX
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP;


-- CREATE MATERIALIZED VIEW
CREATE OR REPLACE MATERIALIZED VIEW EXERCISE_DB.PUBLIC.PARTS_MV AS (
    SELECT 
        AVG(PS_SUPPLYCOST)  AS PS_SUPPLYCOST_AVG,
        AVG(PS_AVAILQTY)    AS PS_AVAILQTY_AVG,
        MAX(PS_COMMENT)     AS PS_COMMENT_MAX
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP
);


-- QUERY MATERIALIZED VIEW AND COMPARE PERFORMANCE (EXECUTION TIME: 519MS)
SELECT * FROM EXERCISE_DB.PUBLIC.PARTS_MV;