USE WAREHOUSE COMPUTE_WH;


-- CREATE READER ACCOUNT
CREATE MANAGED ACCOUNT SHARE_ACCT
    ADMIN_NAME = SHARE_ACCT,
    ADMIN_PASSWORD = 'SHARE-ACCT-PW'
    TYPE = READER;


-- SHOW ACCOUNTS
SHOW MANAGED ACCOUNTS;


-- SHARE DATA WITH READER ACCOUNTS
ALTER SHARE ORDERS_SHARE
    ADD ACCOUNT = <'ACCOUNT-ID'>
    SHARE_RESTRICTIONS = FALSE; -- OVERRIDES RESTRICTION FOR BUSINESS CRITICAL ACCTS
    

-- ADDITIONAL STEPS IN SHARE ACCOUNT
// CREATE A DATABASE & SCHEMA USING SHARE
// CREATE A VIRTUAL WAREHOUSE FOR COMPUTE RESOURCES