USE WAREHOUSE COMPUTE_WH;


-- CREATE VIEW
CREATE OR REPLACE SECURE VIEW DEMO_DB_SHARE.PUBLIC.CUSTOMER_VIEW AS (
    SELECT
        FIRST_NAME,
        LAST_NAME,
        EMAIL
    FROM DEMO_DB.PUBLIC.CUSTOMERS
    WHERE JOB != 'DATA SCIENTIST'
);


SELECT * FROM DEMO_DB_SHARE.PUBLIC.CUSTOMER_VIEW;


-- CREATE SHARE OBJECT
CREATE OR REPLACE SHARE CUSTOMER_SHARE;


-- GRANT USAGE
GRANT USAGE ON DATABASE DEMO_DB_SHARE TO SHARE CUSTOMER_SHARE;
GRANT USAGE ON SCHEMA DEMO_DB_SHARE.PUBLIC TO SHARE CUSTOMER_SHARE;


-- GRANT SELECT PERMISSION ON VIEW
GRANT SELECT ON VIEW  DEMO_DB_SHARE.PUBLIC.CUSTOMER_VIEW TO SHARE CUSTOMER_SHARE;


-- ADD ACCOUNT TO SHARE
ALTER SHARE CUSTOMER_SHARE
    ADD ACCOUNT = <'ACCOUNT-ID'>